name: "eposwa"
description: "A new Flutter project."
publish_to: "none"
version: "1.0.0+1"
environment:
  sdk: "^3.12.2"
dependencies:
  flutter:
    sdk: "flutter"
  cupertino_icons: "^1.0.8"
  window_manager: "^0.4.0"
  drift: "^2.24.1"
  sqlite3_flutter_libs: "^0.5.24"
  sqlite3: "^3.5.2"
  path_provider: "^2.1.5"
  path: "^1.9.1"
  crypto: "^3.0.6"
  archive: "^4.2.0"
  file_selector: "^0.9.4+1"
  file_picker: "^10.1.9"
  shared_preferences: "^2.3.3"
  inno_build: "^0.4.0"
  package_info_plus: ^9.0.1
dev_dependencies:
  flutter_test:
    sdk: "flutter"
  flutter_lints: "^6.0.0"
  drift_dev: "^2.24.1"
  build_runner: "^2.4.13"
  msix: "^3.18.0"
msix_config:
  display_name: "eposwa"
  publisher_display_name: "Keperawatan UMS"
  identity_name: "ums.keperawatan.eposwa"
  logo_path: "assets\\images\\ums.png"
  certificate_path: "windows\\signing\\eposwa_cert.pfx"
  publisher: "CN=Keperawatan UMS, O=Universitas Muhammadiyah Surakarta, C=ID"
  capabilities: null
flutter:
  uses-material-design: true
  assets:
    - "assets/fonts/"
    - "assets/images/"
  fonts:
    - family: "Inter"
      fonts:
        - asset: "assets/fonts/Inter-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Inter-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Inter-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Inter-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/InterVariable.ttf"
inno_build:
  app_id: "9fc9e029-c2e1-4176-a798-63a310d75be7"
